# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      minor-and-patch-updates:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
    schedule:
      interval: 'monthly'
      time: '06:00'
    allow:
      - dependency-name: '@metamask/*'
    target-branch: 'master'
    versioning-strategy: 'increase-if-necessary'
    open-pull-requests-limit: 10
